### ISSUE TITLE
The reference in bin/setup-hadoop-pseudo-mode.sh, to the hadoop distribution to download is outofdate

### ISSUE THREAD

**Issue by svcarlsen** [vinaygoel/ars-workshop#3]
In bin/setup-hadoop-pseudo-mode.sh, either
change the hadoop version to hadoop-2.7.1 
or 
change hadoop_stable_mirror to http://mirror.nexcess.net/apache/hadoop/common/$hadoop_version/$hadoop_version.tar.gz

**Comment by vinaygoel** [comment]
Made it configurable -- https://github.com/vinaygoel/ars-workshop/commit/eb9bc3b2b8ebe15ac6217ad269b5ba5914ea6dad

Thanks!

**Comment by svcarlsen** [comment]
No problem!
